I had to build the docker config.json outside of the kaniko image as the image does not have apk to install the aws cli

diff --git a/.ci/app.yml b/.ci/app.yml
--- a/.ci/app.yml
+++ b/.ci/app.yml
@@ -41,7 +41,9 @@ meta:
 ecr_auth_preprod:
   stage: build
   image: alpine:3.20
-  extends: .aws_oidc_auth
+  extends:
+    - .app_rules_develop
+    - .aws_oidc_auth
   variables:
     AWS_ROLE_ARN: $AWS_ROLE_ARN_PREPROD
     AWS_REGION: eu-west-2
@@ -68,7 +70,7 @@ kaniko_build_preprod:
     - .aws_oidc_auth
   variables:
     AWS_ROLE_ARN: $AWS_ROLE_ARN_ECR_PREPROD
-  needs: ["meta"]
+  needs: ["meta", "ecr_auth_preprod"]
   script:
     # authenticate kaniko to ECR
     - mkdir -p /kaniko/.docker
@@ -96,3 +98,52 @@ kaniko_build_preprod:
     paths:
       - image.digest
     expire_in: 7 days
+
+.app_rules_tag_v:
+  rules:
+    - if: '$CI_COMMIT_TAG =~ /^v.*/'
+      when: on_success
+    - when: never
+
+promote_to_prod:
+  stage: build
+  image: alpine:3.20
+  extends:
+    - .app_rules_tag_v
+    - .aws_oidc_auth
+  variables:
+    AWS_ROLE_ARN: $AWS_ROLE_ARN_ECR_PROD_PROMOTE
+    AWS_REGION: eu-west-2
+  script:
+    - apk add --no-cache aws-cli jq
+
+    # Copy manifest from preprod:<sha> to prod:<tag> without rebuilding
+    - |
+      SRC_TAG="${CI_COMMIT_SHA}"
+      DST_TAG="${CI_COMMIT_TAG}"
+
+      set -euo pipefail
+  
+      echo "Promoting ${PREPROD_ECR_REPO}:${SRC_TAG} -> ${PROD_ECR_REPO}:${DST_TAG}"
+      
+      MANIFEST="$(aws ecr batch-get-image \
+      --region "${AWS_REGION}" \
+      --repository-name "${PREPROD_ECR_REPO}" \
+      --image-ids imageTag="${SRC_TAG}" \
+      --query 'images[0].imageManifest' \
+      --output text 2>/tmp/batch_get_err || true)"
+      
+      if [ -z "${MANIFEST}" ] || [ "${MANIFEST}" = "None" ]; then
+        echo "ERROR: Could not fetch manifest for ${PREPROD_ECR_REPO}:${SRC_TAG}"
+        echo "AWS CLI error (if any):"
+        cat /tmp/batch_get_err || true
+        exit 1
+      fi
+
+      aws ecr put-image \
+        --region "${AWS_REGION}" \
+        --repository-name "${PROD_ECR_REPO}" \
+        --image-tag "${DST_TAG}" \
+        --image-manifest "${MANIFEST}"
+
+      echo "Done."
